"""empty message

Revision ID: 02fd95546b6f
Revises: 0c1513a17cb2
Create Date: 2016-12-20 14:33:14.027000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fd95546b6f'
down_revision = '0c1513a17cb2'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ports', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ports', 'body_html')
    ### end Alembic commands ###
